[supervisord]
nodaemon=true
logfile=/dev/fd/1
logfile_maxbytes=0

[program:xvfb]
command=/usr/bin/Xvfb :0 -screen 0 %(ENV_SCREEN_W)sx%(ENV_SCREEN_H)sx%(ENV_SCREEN_D)s -ac +extension GLX +render -noreset
autorestart=true
priority=10

[program:fluxbox]
environment=DISPLAY=%(ENV_DISPLAY)s
command=/usr/bin/fluxbox -display %(ENV_DISPLAY)s
autorestart=true
priority=20

[program:x11vnc]
command=/usr/bin/x11vnc -display %(ENV_DISPLAY)s -forever -shared -nopw -rfbport %(ENV_VNC_PORT)s -quiet
autorestart=true
priority=30

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc/ %(ENV_NO_VNC_PORT)s localhost:%(ENV_VNC_PORT)s
autorestart=true
priority=40

[program:app]
environment=DISPLAY=%(ENV_DISPLAY)s
directory=/app
command=/usr/local/bin/start-app.sh
autorestart=true
startretries=999
priority=50
